### ISSUE TITLE
 POST /webhook 404 Not Found

### ISSUE THREAD

**Issue by Rizwanali324** [adarshb3/Virtual-Try-On-Application-using-Flask-Twilio-and-Gradio#2]
while i setup the webhook nothing is responded by model

**Comment by adarshb3** [comment]
Make sure you're using ngrok for exposing your local flask server and then check if your sandbox is registered with that url in the 'sandbox configuration' as the url for 'when the message comes in'. https://www.twilio.com/docs/whatsapp/sandbox
